import type { Metadata } from "next";

import "@styles/globals.css";

export const metadata: Metadata = {
  title: "active",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className='h-full antialiased'
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
